apiVersion: v1
kind: Service
metadata:
  name: orchestration
spec:
  type: NodePort
  selector:
    app: orchestration
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
